# Generated by Django 5.0.7 on 2024-07-28 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boks', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user_id',
            new_name='user',
        ),
    ]
